decred/gominer

blake256.cl, config.go, device.go, getwork.go, miner.go, stratum.go
Stratum mining has been made operational. Intensity was a float64;
it has been changed to a uint32 and alternatively the user may elect
to instead directly set the work size, which must be a multiple of
32.
=> Fix stratum mining and intensity

stratum.go
Errors are now thrown if the passed pool difficulty is not a whole number. Fixes #28.
=> Fix some stratum difficulty bugs

miner.go, stratum.go
=> Correctly increment rejected shares

version.go
Switch from alpha to beta while we are at it.
=> Bump to v0.2.0

.gitignore, README.md, glide.lock, glide.yaml
=> Use glide to manage dependancies.

sample-gominer.conf
=> Add all options to sample config.

calibrate.go, device.go, getwork.go, log.go, miner.go, stratum/log.go, stratum/stratum.go, util/util.go, work/work.go
This commit moves the stratum code to one package and the work type to
another package.
Closes #11
=> Create stratum and work packages.

device.go, getwork.go, miner.go, stratum/stratum.go
This commit just handles the poolwork structure.
When done:
Fixes #33
=> Add locks to racy data structures.

getwork.go, main.go, miner.go, stratum/stratum.go
=> Clean up logging.

miner.go
=> Remove erroneous waitgroup Done in Stop

GNUmakefile, README.md, cldevice.go, compat.h, config.go, cuda_helper.h, cudevice.go, decred.cu, device.go, glide.lock, miner.go, miner.h, sph/blake.c, sph/sph_blake.h, sph/sph_types.h
Modelled partly after ccminer.
Contains work by jrick and jcv.
=> Initial support for cuda mining.

cudevice.go
=> Clean up some old or incorrect comments.

cl/context.go, cudevice.go
from
https://github.com/rainliu/gocl/commit/5e6a128b97580c6ffdb9eafd8c35ed6d0e074dbb
Also makes go vet happy.
=> fix cgo Go pointers issue

GNUmakefile, README.windows, cgo_flags.go, cl/buffer.go, cl/cgo_flags.go, cl/cl.go, cl/cl.h, cl/context.go, cl/device.go, cl/event.go, cl/event11.go, cl/image.go, cl/image11.go, cl/kernel.go, cl/kernel1x.go, cl/memory.go, cl/platform.go, cl/program.go, cl/program11.go, cl/queue.go, cl/queue1x.go, cl/sampler.go, cl/sampler1x.go, cudakernel_static.go, cudakernel_windows.go, cudevice.go, decred.cu, decred.h, nvml/cgo_flags.go, nvml/nvml.go
This also cleans up cgo usage across the entire project.
Fixes #108.
=> Implement CUDA on windows, Fixes #108

device.go, miner.go
=> Remove unneeded word in INFO log line

sample-gominer.conf
=> Update sample config with all new options.

cudakernel_static.go, cudakernel_windows.go, cudevice.go, device.go, glide.lock, glide.yaml, stratum/stratum.go
=> Switch to standalone upstream CUDA libs.

config.go, main.go
Following example of dcrd and dcrwallet.
Closes #145
=> Add go version to version info

config.go, glide.lock, glide.yaml, log.go, main.go
While there, update deps.
Closes #156
=> Swtich to new logging backend.

config.go
This matches the change in dcrd for the same thing.
Closes #159
=> Check valid log level using btclog.

Gopkg.lock, config.go
While here, update deps and fix PowLimit on !mainnet
=> Use testnet3

README.md
Also, no pool support at the moment.
=> README: Fix a few typos.

README.md
=> README: Add user reported hashrates.
